{{- if .Values.services.user.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "securecart.fullname" . }}-user
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: "{{ .Values.image.repository }}-user:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.user.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.services.user.port }}
{{- end }}
